# Generated by Django 4.2.3 on 2023-08-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('estrellas', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
    ]
