# Generated by Django 4.2.3 on 2023-08-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudad',
            name='superficie',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
