# Generated by Django 4.2.3 on 2023-08-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hotel',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
