# Generated by Django 4.2.3 on 2023-08-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_reserva_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='hotel',
            field=models.CharField(choices=[('sky', 'Skybay Hotel Gyeongpo'), ('hotel2', 'Hotel 2'), ('hotel3', 'Hotel 3')], max_length=20),
        ),
    ]
