# Generated by Django 4.2.3 on 2023-08-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_reserva_hotel_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='fotoPerfil',
        ),
        migrations.AddField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default=0, upload_to='avatares'),
            preserve_default=False,
        ),
    ]
